### ISSUE TITLE
Missing jpeg2000 driver in gdal

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/nersc-vagrant#10]
```
import gdal
f = '/home/vagrant/ncep_gfs_downloads/gfs_4_20140326_0600_000.grb2'
ds = gdal.Open(f)
ERROR 4: `/vsimem/work.jpc' not recognised as a supported file format.

dec_jpeg2000: Unable to open JPEG2000 image within GRIB file.
Is the JPEG2000 driver available?
```

The grib file is available at ftp://ftp.nersc.no/pub/nansat/test_data/ncep/gfs_4_20140326_0600_000.grb2

**Comment by mortenwh** [comment]
To be solved in conda-recipes repos

**Comment by marineanalytica** [comment]
Hi,
I got the same error: 

ERROR 4: `/vsimem/work_grib_00000174D4062EDB.jpc' not recognized as a supported file format.
dec_jpeg2000: Unable to open JPEG2000 image within GRIB file.
Is the JPEG2000 driver available?g2_getfld: return from g2_unpack7 = 7
ERROR 4: multi_reanal.glo_30m_ext.hs.199210.grb2 is a grib file, but no raster dataset was successfully identified.

How did you solve it?
Gerardo
