### ISSUE TITLE
Need gdal version 2.1

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/nersc-vagrant#15]
Gdal 2.1 has a sentinel driver. Can that be added to miniconda instead of the present v2.0? At least for the develop vm?

**Comment by aleksandervines** [comment]
http://www.gdal.org/frmt_sentinel2.html

gdal 2.1 is not yet released: https://trac.osgeo.org/gdal/roadmap

It is of course possible to download the current master source and compile, but it is not a stable release.

I don't like the idea of running different versions on develop/testintegration/travis (I'm fine with course doing it). But then again, I don't like the idea of using a non-stable release on all of them either. 

What do you need it for?
- If you do need the sentinel 2 support to actually develop Nansat, then we might have to run the non-stable version on all?
- If you need it only for some specific stuff you are working on, and not going to push to Nansat, then it would probably be best to leave the default develop machine with a stable release, but perhaps add an option to install the 2.1 version?

**Comment by mortenwh** [comment]
Maybe using installation of the 2.1 version in the develop machine as an
option is the best. Then we don't interfere with other existing systems. It
would be great if you could do that :)

**Comment by mortenwh** [comment]
The driver does not provide calibrated NRCS, nor incidence angles. Useless at the moment. Closing the issue.
