### ISSUE TITLE
default vm/version

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/nersc-vagrant#19]
If we are advocating this vagrant configuration as a method of installing nansat, then either develop should not be the default vm, or master should be the default version/branch on develop.

**Comment by mortenwh** [comment]
The develop vm should use nansat and nansen-cloud develop branches, as now
(right?). Do we have a vm running nansat master? If not, we should probably
make it... At least don't install nansat master on the develop vm...

**Comment by aleksandervines** [comment]
For some reason I thought develop was primary, but it was course..
