### ISSUE TITLE
Error with current setup of testconda on windows

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/nersc-vagrant#4]
As the shared folder is mounted from a windows file system, it does not support symlinking. You can therefore not install miniconda there.

Why do we want to install miniconda in the shared folder on the vm?

**Comment by aleksandervines** [comment]
Testing with conda_dir: /home/vagrant/miniconda works.

**Comment by akorosov** [comment]
It takes long time after each destroy to download all conda intallers. To 'cache' the miniconda.sh and other packages I install it in shared folder. After I do 'destroy' shared folder and it's contents is kept and next time 'up' is much faster.
We can of course sacrifice speed to make it compatible with running from windows. At least that has to be done for miniconda dir.

**Comment by akorosov** [comment]
Hmm, I found how to 'cache' packages:
http://stackoverflow.com/questions/22878104/is-it-possible-to-conda-install-with-dependencies-completely-offline/22917229#22917229

And hot to free up space in the base box:
http://stackoverflow.com/questions/27567560/anaconda-vs-miniconda-space

**Comment by akorosov** [comment]
That method doesn't work. Suddenly many dependency errors appeared. Let's try to install minicond in home directory but move miniconda/pkgs to the shared directory and symlink.

**Comment by akorosov** [comment]
That role can be in the testconda only. The base box will keep pkgs inside but will clean them before packaging.

**Comment by akorosov** [comment]
That 'caching' requires too much testing. Speeding up conda slows down me.
miniconda will be installed in shared dir for 'testconda' machine only. 'base' and other boxes will place it to /home/vagrant/miniconda

**Comment by akorosov** [comment]
Windows users can change 'conda_dir' variable in provisioning/group_vars/testconda

**Comment by akorosov** [comment]
Ok, I got it! Caching is done in several steps rather than in one:
1. install conda
2. copy package files *.bz2 from cache (e.g. shared/conda_pkgs) into miniconda/pkgs
3. conda installs all the packages
4. copy *.bz2 and urls.txt from miniconda/pkgs into a cache (e.g. shared/conda_pkgs)
