### ISSUE TITLE
error when role is not found

### ISSUE THREAD

**Issue by aleksandervines** [nansencenter/nersc-vagrant#8]
If you define a role, e.g. nersc-thredds, it needs to exist. 

I don't think we should have this role here, it should probably just be added in the thredds-repository

**Comment by akorosov** [comment]
Then we would have to have Vagrantfile, hosts and site.yml also. I though it is better to avoid duplicating and group everything related to nersc-vagrant in one place. Maybe the best is to remove sensitive information from nersc-thredds and make it public (i.e. move to nersc-vagrant/.../thredds)

**Comment by aleksandervines** [comment]
This is done
